[project]
name = 'Energy-Trading-Network'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.consumption-metering]
path = 'contracts/consumption-metering.clar'
clarity_version = 2
epoch = 2.5

[contracts.grid-balancing]
path = 'contracts/grid-balancing.clar'
clarity_version = 2
epoch = 2.5

[contracts.producer-registration]
path = 'contracts/producer-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
